### ISSUE TITLE
Don't show the user profile survey after logins by registered users

### ISSUE THREAD

**Issue by asiripanich** [asiripanich/e-mission-phone#19]

**Comment by atton16** [comment]
This has been done. However, due to the way the synchronization work, if you remove the app and reinstall the app then the data will not arrived in time. So the system as you as if you are the new user. Unfortunately, if we are pushing this feature forward we will need to consult the main repository to make some changes on function `UnifiedDataLoader.getUnifiedMessagesForInterval`.
